---
title: Datasets
---

We maintain several curated datasets that are created from existing datasets, mostly provincial and national scale datasets. These are described below.

## Cross-boundary datasets (BC-Yukon)

- Name: bp_datasets.gpkg
- Updated: October 2023
- Coverage: entire Yukon + northern BC
- NAD_1983_Yukon_Albers
- WKID: 3578 Authority: EPSG
- Download (with permission): [gpkg](https://drive.google.com/open?id=1YD9eRFePQF8xXAqS1PAl3bD8cP9EWwvS&usp=drive_fs)

```
Available layers:
  layer_name     geometry_type features fields             crs_name
1        fda     Multi Polygon        1      0 NAD83 / Yukon Albers
2    sd_line Multi Line String   265838      2 NAD83 / Yukon Albers
3    sd_poly     Multi Polygon   114132      2 NAD83 / Yukon Albers
4   ifl_2000                         33      4 NAD83 / Yukon Albers
5   ifl_2020                         31      4 NAD83 / Yukon Albers
6      fires     Multi Polygon     3526     28 NAD83 / Yukon Albers
```

## Yukon datasets

- Name: yt_datasets.gdb
- Updated: October 2023
- Coverage: entire Yukon
- NAD_1983_Yukon_Albers
- WKID: 3578 Authority: EPSG

```
Available layers:
                            layer_name     geometry_type features fields             crs_name
1                         Fire_History     Multi Polygon     2065     11 NAD83 / Yukon Albers
2   Surface_Disturbance_Areal_Features     Multi Polygon    10382     12 NAD83 / Yukon Albers
3  Surface_Disturbance_Linear_Features Multi Line String    70930     13 NAD83 / Yukon Albers
4   Surface_Disturbance_Mapping_Extent     Multi Polygon       15      5 NAD83 / Yukon Albers
5          Yukon_Planning_Regions_250k     Multi Polygon       10      4 NAD83 / Yukon Albers
6               Yukon_Borders_Surveyed Multi Line String     1177     10 NAD83 / Yukon Albers
7                 Mining_Districts_50k     Multi Polygon        4      9 NAD83 / Yukon Albers
8                                  bnd     Multi Polygon        1      2 NAD83 / Yukon Albers
9                   Canada_Access_2010     Multi Polygon        7      6 NAD83 / Yukon Albers
10                     Global_IFL_2000     Multi Polygon       27      4 NAD83 / Yukon Albers
11                     Global_IFL_2020     Multi Polygon       25      4 NAD83 / Yukon Albers
12              Global_IFL_forest_zone     Multi Polygon        2      3 NAD83 / Yukon Albers
13                             NTS_50k     Multi Polygon      827      6 NAD83 / Yukon Albers
14                         NTS_50k_9x9     Multi Polygon    66987      4 NAD83 / Yukon Albers
15                   Quartz_Claims_50k     Multi Polygon   163696     16 NAD83 / Yukon Albers
16                   Placer_Claims_50k     Multi Polygon    29605     15 NAD83 / Yukon Albers
17                  Yukon_Road_Network Multi Line String     8046     25 NAD83 / Yukon Albers
18                Railroads_50k_Canvec Multi Line String       24     76 NAD83 / Yukon Albers
19                          Trails_50k Multi Line String    24231     13 NAD83 / Yukon Albers
20 Historic_Silviculture_Inventory_50k     Multi Polygon     1104      8 NAD83 / Yukon Albers
21                          caribou_yt     Multi Polygon       26      5 NAD83 / Yukon Albers
22                                FDA9     Multi Polygon        9      3 NAD83 / Yukon Albers
23                            lfn_ipca     Multi Polygon        3      7 NAD83 / Yukon Albers
24                 caribou_yt_woodland     Multi Polygon       27      5 NAD83 / Yukon Albers
25                               NHN18     Multi Polygon       18     19 NAD83 / Yukon Albers
26              Waterbodies_50k_Canvec     Multi Polygon   364776     32 NAD83 / Yukon Albers
27                      Waterbodies_1M     Multi Polygon    19702     19 NAD83 / Yukon Albers
28                     Watercourses_1M Multi Line String    53638     20 NAD83 / Yukon Albers
29             Watercourses_50k_Canvec Multi Line String  1069837     26 NAD83 / Yukon Albers
30                             Streams Multi Line String     3317     35 NAD83 / Yukon Albers
31                          Catchments     Multi Polygon     2516     37 NAD83 / Yukon Albers
```

## BC datasets

- Name: bc_datasets.gdb
- Updated: October 2023
- Coverage: LRB region of BC
- NAD_1983_BC_Environment_Albers
- WKID: 3005 Authority: EPSG
- veg_comp_poly and vri are only available for the FDA10 portion of the LRB

```
Available layers:
          layer_name             geometry_type features fields          crs_name
1         caribou_bc 3D Measured Multi Polygon       25     13 NAD83 / BC Albers
2              mines             Multi Polygon       13      6 NAD83 / BC Albers
3                 bc             Multi Polygon        1      8 NAD83 / BC Albers
4                bnd             Multi Polygon        1      2 NAD83 / BC Albers
5              roads      3D Multi Line String   130715     91 NAD83 / BC Albers
6          cutblocks             Multi Polygon     7990     10 NAD83 / BC Albers
7 transmission_lines         Multi Line String       48     10 NAD83 / BC Albers
8   recreation_lines         Multi Line String      117     29 NAD83 / BC Albers
9           cef_2021             Multi Polygon    90199     13 NAD83 / BC Albers
```

## Canada datasets

- Name: ca_datasets.gdb
- Updated: October 2023
- Coverage: Canada
- Canada_Albers_Equal_Area_Conic
- WKID: 102001 Authority: Esri

```
Available layers:
                layer_name             geometry_type features fields                       crs_name
1            Ecozones_2019             Multi Polygon       18      5 Canada_Albers_Equal_Area_Conic
2          Ecoregions_2019             Multi Polygon      215      8 Canada_Albers_Equal_Area_Conic
3                NHN_Index             Multi Polygon     1342     19 Canada_Albers_Equal_Area_Conic
4              Large_lakes             Multi Polygon      128      9 Canada_Albers_Equal_Area_Conic
5              Great_lakes             Multi Polygon        5      9 Canada_Albers_Equal_Area_Conic
6                  NTS_50k             Multi Polygon    18865      7 Canada_Albers_Equal_Area_Conic
7          HydroBasins_L12             Multi Polygon    75215      5 Canada_Albers_Equal_Area_Conic
8          Canada_statscan             Multi Polygon       13      8 Canada_Albers_Equal_Area_Conic
9  catchments_boreal_vPB25             Multi Polygon   193314     37 Canada_Albers_Equal_Area_Conic
10         Canada_hexagons             Multi Polygon     1455      6 Canada_Albers_Equal_Area_Conic
11           CPCAD_Dec2021             Multi Polygon    12199     33 Canada_Albers_Equal_Area_Conic
12      NFDB_poly_20210707 3D Measured Multi Polygon    59539     28 Canada_Albers_Equal_Area_Conic
13              Y2Y_region             Multi Polygon        1      4 Canada_Albers_Equal_Area_Conic
14                Ecozones             Multi Polygon       25      9 Canada_Albers_Equal_Area_Conic
15            Ecoprovinces             Multi Polygon       68      7 Canada_Albers_Equal_Area_Conic
16              Ecoregions             Multi Polygon      218     10 Canada_Albers_Equal_Area_Conic
17           Canada_boreal             Multi Polygon     6575      5 Canada_Albers_Equal_Area_Conic
18         Global_IFL_2020             Multi Polygon      254      4 Canada_Albers_Equal_Area_Conic
19         Global_IFL_2000             Multi Polygon      268      4 Canada_Albers_Equal_Area_Conic
20      Canada_access_2010             Multi Polygon       46      6 Canada_Albers_Equal_Area_Conic
21         Canada_IFL_2013             Multi Polygon      317      7 Canada_Albers_Equal_Area_Conic
22  Global_IFL_forest_zone             Multi Polygon        2      3 Canada_Albers_Equal_Area_Conic
23   Canada_IFL_study_area             Multi Polygon     5170      3 Canada_Albers_Equal_Area_Conic
24         Canada_IFL_2000             Multi Polygon      354      4 Canada_Albers_Equal_Area_Conic
25        Sentinel_2_index 3D Measured Multi Polygon     1575      4 Canada_Albers_Equal_Area_Conic
26               Ecozones3             Multi Polygon        3      9              NAD83 / BC Albers
27          Ecozones3_dslv             Multi Polygon        1      2              NAD83 / BC Albers
```